name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test_release:
    name: Test release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            zip_name: adelay-linux.zip
          - os: macos-latest
            zip_name: adelay-mac.zip
          - os: windows-latest
            zip_name: adelay-win.zip

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install Windows dependencies
        if: matrix.os == 'windows-latest'
        run: |
          choco install curl
          choco install unzip

      - name: Validate plugin
        shell: bash
        run: |
          npm install -g
          curl -L -o ./plugin.zip https://github.com/studiorack/studiorack-plugin/releases/latest/download/${{ matrix.zip_name }}
          unzip ./plugin.zip -d ./tests
          studiorack validate "./tests/**/*.{vst,vst3}" --json
          studiorack validate "./tests/**/*.{vst,vst3}" --summary
          studiorack validate "./tests/**/*.{vst,vst3}" --txt
          studiorack validate "./tests/**/*.{vst,vst3}" --zip
