name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test_release:
    name: Test release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            zip_name: plugin-linux.zip
          - os: macos-latest
            zip_name: plugin-mac.zip
          - os: windows-latest
            zip_name: plugin-win.zip

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Windows dependencies
        if: matrix.os == 'windows-latest'
        run: |
          choco install curl
          choco install unzip

      - name: Validate plugin
        shell: bash
        run: |
          npm install -g
          curl -o ./plugin.zip https://github.com/studiorack/studiorack-plugin/releases/latest/download/${{ matrix.zip_name }}
          unzip ./plugin.zip -d ./tests
          studiorack validate "./tests/**/*.{vst,vst3}"
          studiorack validate "./tests/**/*.{vst,vst3}" --metadata
